"""
Exception and Traceback
ðŸ”‘ An uncaught exception will quit the running Python program
ðŸ”‘ Use try and except to catch exceptions
ðŸ”‘ Try to catch the exceptions as specific as possible (SyntaxError, ValueError...)
ðŸ”‘ Use "as" to access the exception

ðŸ“š Resources:
https://www.learnpython.dev/02-introduction-to-python/175-running-code/50-exceptions/
"""
# ðŸ›  Catch a value error
# try:
# 	int("a")
# except ValueError:
# 	print("Cannot convert that value into string")

# ðŸ›  Access an exception
# try:
# 	int("a")
# except ValueError as error:
# 	print("Cannot convert that value into string", error)